### PR TITLE
Ignore interfaces

### PR DESCRIPTION
**Pull request by Brom95**
Add ability to ignore interfaces for https://github.com/patrickklaeren/AutoRegisterInject/issues/2

### CODE REVIEW

**Comment by patrickklaeren** [comment]
Thanks for your contribution. I've been away and just got to this.

It seems there's 3 new interfaces for this. I had expected to implement this myself so was light on implementation detail.

This works in a scenario where I implement one interface, however doesn't work too well if I have multiple and want to register with a specific interface.

The intention was for the following:

```cs
[RegisterScoped, IgnoreInterface(typeof(IFoo))]
class Foo : IFoo, IBar;
```

Where we register `Foo` with `AddScoped<IBar, Foo>();`

I hope this makes sense?

**Comment by Brom95** [comment]
Thank you for answer!
What about case when we need to ignore several interfaces? May be better if `IgnoreInterface` accept list of interfaces?

P.S. I apologize in advance for my English. I'm not native speaker.

**Comment by patrickklaeren** [comment]
> Thank you for answer! What about case when we need to ignore several interfaces? May be better if `IgnoreInterface` accept list of interfaces?
> 
> P.S. I apologize in advance for my English. I'm not native speaker.

Yeah, I see this as `[IgnoreInterface(type(IFoo), typeof(IBar))]`

**Comment by patrickklaeren** [comment]
This is being closed in favour of #4 

Thank you for your contribution, it has helped aid the design of the future of this source generator.

**Pull request closed without merging**
